# .github/dependabot.yml
version: 2
updates:
  # 1) GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "07:00", timezone: "Europe/Brussels" }
    target-branch: "main"
    labels: ["dependencies", "github_actions"]
    groups:
      actions-weekly:
        patterns: ["*"]

  # 2) Composer (Laravel)
  - package-ecosystem: "composer"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "07:10", timezone: "Europe/Brussels" }
    target-branch: "main"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      laravel-core:
        patterns: ["laravel/*", "illuminate/*"]
      dev-tools:
        patterns: ["phpunit/*", "pestphp/*", "phpstan/*", "nunomaduro/*"]

  # 3) Docker (si images)
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "07:20", timezone: "Europe/Brussels" }
    target-branch: "main"
