name: "CI – Backend (PR)"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [staging, main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "LICENSE"
  workflow_dispatch:

# Permissions minimales + écriture pour publier checks/annotations sur la PR
permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pr:
    # Ne tourne pas sur les PR en brouillon
    if: ${{ github.event.pull_request.draft == false }}
    name: "Backend PR checks"
    uses: obatis/.github/.github/workflows/backend-ci-pr.yml@main
    with:
      php-version: "8.3"
      laravel-version: "12.x"
      # L'env 'staging' est utilisé pour les PR (pas de secrets nécessaires)
      environment: "staging"
      # Laisse à 0 ici : les seuils seront activés au point 14 (gating)
      coverage-threshold: 0
      run-migrations: false
    # Pas de secrets pour les PR (sécurité forks)
    secrets: {}
