name: "CI – Frontend Flutter (PR)"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [staging, main]
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "LICENSE"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pr:
    if: ${{ github.event.pull_request.draft == false }}
    name: "Frontend PR checks"
    uses: obatis/.github/.github/workflows/frontend-ci-pr.yml@main
    with:
      flutter-channel: "stable"
      # Optionnel: verrouiller une version si besoin
      # flutter-version: "3.22.x"
      environment: "staging"
      coverage-threshold: 0
      build-web: false   # build complet activé plus tard (point 14)
    secrets: {}
