name: "CI – Infra Ansible (PR)"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [staging, main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "LICENSE"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pr:
    if: ${{ github.event.pull_request.draft == false }}
    name: "Infra PR checks"
    uses: obatis/.github/.github/workflows/infra-ci-pr.yml@main
    with:
      ansible-version: "9"
      run-ansible-lint: true
      run-yamllint: true
      run-molecule: false   # les tests Molecule/idempotence pourront être activés au point 14
      environment: "staging"
    secrets: {}
