name: "CI Infra (Ansible) – template"
on:
  pull_request: { branches: [staging, main] }
jobs:
  call:
    uses: Obatis/.github/.github/workflows/ci-infra-ansible.yml@main
    with:
      runner_label: 'staging'
