name: CI Backend (Laravel)

on:
  workflow_call:
    inputs:
      php:          { type: string,  default: "8.3",     required: false }
      runner_label: { type: string,  default: "staging", required: false }
      use_self_hosted: { type: boolean, default: false, required: false }

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  backend-ci:
    name: backend-ci
    runs-on: ${{ inputs.use_self_hosted && fromJSON(format('["self-hosted","linux","{0}"]', inputs.runner_label)) || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          tools: composer:v2
          extensions: mbstring, intl, gd, pdo_mysql
          coverage: none

      - name: Install Composer deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Préparer l'app
        run: |
          cp -n .env.example .env || true
          php artisan key:generate || true

      - name: Tests
        run: php artisan test --parallel --stop-on-failure
