---
name: CI Backend (Laravel)

on:
  workflow_call:
    inputs:
      # runner
      use_self_hosted:
        type: boolean
        default: false
        required: false
      runner_label:
        type: string
        default: "staging"
        required: false

      # toolchain
      node_version:
        type: string
        default: "20"
        required: false

      # toggles
      markdown_lint:
        type: boolean
        default: true
        required: false
      link_check:
        type: boolean
        default: false
        required: false
      build_docs:
        type: boolean
        default: false
        required: false

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  backend-ci:
    name: backend-ci
    # runner GitHub-hosted ou self-hosted selon l'input
    runs-on: ${{ inputs.use_self_hosted && fromJSON(format('["self-hosted","linux","{0}"]', inputs.runner_label)) || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
        if: ${{ inputs.markdown_lint || inputs.link_check || inputs.build_docs }}

      # ——— Lint Markdown (optionnel)
      - name: Lint Markdown
        if: ${{ inputs.markdown_lint }}
        run: |
          npm --version || (corepack enable && corepack prepare npm@latest --activate)
          npx --yes markdownlint-cli@0.41.0 "**/*.md" --ignore "node_modules"

      # ——— Link checker (optionnel, exemple simple)
      - name: Check links
        if: ${{ inputs.link_check }}
        run: echo "Link check ici (ajoute ta logique ou une action dédiée)"

      # ——— Build docs (optionnel, exemple simple)
      - name: Build docs
        if: ${{ inputs.build_docs }}
        run: echo "Build docs ici (ajoute ta logique de génération)"

