name: CI Backend (Laravel)

on:
  workflow_call:
    inputs:
      runner_label:      { type: string,  default: "ubuntu-latest", required: false }
      use_self_hosted:   { type: boolean, default: false,           required: false }
      run_phpstan:       { type: boolean, default: true,            required: false }
      run_phpcs:         { type: boolean, default: true,            required: false }
      run_tests:         { type: boolean, default: true,            required: false }

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  backend-ci:
    runs-on: ${{ inputs.use_self_hosted
      && fromJSON('["self-hosted","linux","' + inputs.runner_label + '"]')
      || inputs.runner_label }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          extensions: mbstring, intl, pdo, pdo_mysql

      - name: Install deps
        run: composer install --no-interaction --prefer-dist

      - name: PHPStan
        if: ${{ inputs.run_phpstan }}
        run: vendor/bin/phpstan analyse --no-progress || vendor/bin/phpstan --version

      - name: PHPCS
        if: ${{ inputs.run_phpcs }}
        run: vendor/bin/phpcs -q || echo "PHPCS not configured"

      - name: PHPUnit
        if: ${{ inputs.run_tests }}
        run: vendor/bin/phpunit --testdox || echo "PHPUnit not configured"
