name: CI Frontend (Flutter)

on:
  workflow_call:
    inputs:
      channel:       { type: string,  default: "stable",  required: false }
      runner_label:  { type: string,  default: "staging", required: false }
      use_self_hosted: { type: boolean, default: false,  required: false }

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  frontend-ci:
    name: frontend-ci
    runs-on: ${{ inputs.use_self_hosted && fromJSON(format('["self-hosted","linux","{0}"]', inputs.runner_label)) || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.channel }}

      - name: Resolve deps
        run: flutter pub get

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Tests (with coverage)
        run: |
          flutter test --coverage
          test -f coverage/lcov.info || exit 1

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: coverage/lcov.info
          if-no-files-found: error
