name: CI Frontend (Flutter)

on:
  workflow_call:
    inputs:
      runner_label:    { type: string,  default: "ubuntu-latest", required: false }
      use_self_hosted: { type: boolean, default: false,           required: false }
      channel:         { type: string,  default: "stable",         required: false }

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  frontend-ci:
    runs-on: ${{ inputs.use_self_hosted
      && fromJSON('["self-hosted","linux","' + inputs.runner_label + '"]')
      || inputs.runner_label }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.channel }}

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Resolve deps
        run: flutter pub get

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Tests (with coverage)
        run: |
          flutter test --coverage
          test -f coverage/lcov.info || (echo "no coverage file" && exit 1)

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: coverage/lcov.info
          if-no-files-found: error
