name: CI Infra (Ansible)

on:
  workflow_call:
    inputs:
      runner_label:
        type: string
        default: "ubuntu-latest"
        required: false
      run_yamllint:
        type: boolean
        default: true
        required: false
      run_molecule:
        type: boolean
        default: false
        required: false

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  infra-ci:
    runs-on: ${{ inputs.runner_label }}
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip
          pip3 install ansible yamllint molecule

      - name: YAML Lint
        if: ${{ inputs.run_yamllint }}
        run: yamllint .

      - name: Ansible Syntax (optional example)
        run: |
          test -f playbook.yml && ansible-playbook --syntax-check playbook.yml || echo "no playbook.yml"

      - name: Molecule (optional)
        if: ${{ inputs.run_molecule }}
        run: |
          test -d molecule && molecule test || echo "no molecule dir"
