name: CI Ops

on:
  workflow_call:
    inputs:
      runner_label:
        type: string
        default: "ubuntu-latest"
        required: false
      run_linters:
        type: boolean
        default: true
        required: false
      run_security:
        type: boolean
        default: true
        required: false

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  ops-ci:
    runs-on: ${{ inputs.runner_label }}
    steps:
      - uses: actions/checkout@v4

      - name: Shellcheck (bash scripts)
        if: ${{ inputs.run_linters }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y shellcheck
          find . -type f -name "*.sh" -print0 | xargs -0 -r shellcheck

      - name: Markdownlint
        if: ${{ inputs.run_linters }}
        run: |
          npm i -g markdownlint-cli || true
          markdownlint "**/*.md" || true

      - name: Trivy FS scan (security)
        if: ${{ inputs.run_security }}
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: '0'
