name: CI Ops

on:
  workflow_call:
    inputs:
      use_self_hosted:  { type: boolean, default: false }
      runner_label:     { type: string,  default: "staging" }
      node_version:     { type: string,  default: "20" }
      markdown_lint:    { type: boolean, default: true }
      link_check:       { type: boolean, default: false }
      build_docs:       { type: boolean, default: false }

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  ops-ci:
    name: ops-ci
    # ← plus de '+' ici
    runs-on: ${{ inputs.use_self_hosted
      && fromJSON(format('["self-hosted","linux","{0}"]', inputs.runner_label))
      || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4

      # Setup Node avec cache si lockfile présent
      - name: Setup Node (with cache)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm

      # Setup Node sans cache sinon
      - name: Setup Node (no cache)
        if: ${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          elif [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            echo "No lockfile found – skipping install"
          fi

      - name: Lint Markdown
        if: ${{ inputs.markdown_lint }}
        run: npx --yes markdownlint-cli@0.41.0 "**/*.md" --ignore "node_modules"

      - name: Check links (optional)
        if: ${{ inputs.link_check }}
        run: npx --yes markdown-link-check -q '**/*.md'

      - name: Build docs (optional)
        if: ${{ inputs.build_docs }}
        run: npm run docs:build
