name: CI Ops

on:
  workflow_call:
    inputs:
      runner_label:    { type: string,  default: "ubuntu-latest", required: false }
      use_self_hosted: { type: boolean, default: false,           required: false }
      node_version:    { type: string,  default: "20",            required: false }
      markdown_lint:   { type: boolean, default: true,            required: false }
      link_check:      { type: boolean, default: false,           required: false }
      build_docs:      { type: boolean, default: false,           required: false }

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  ops-ci:
    name: ops-ci
    # Pas de concaténation avec '+'
    runs-on: ${{ inputs.use_self_hosted
      && fromJSON(format('["self-hosted","linux","{0}"]', inputs.runner_label))
      || inputs.runner_label }}

    steps:
      - uses: actions/checkout@v5

      # Node seulement si on en a besoin (lint / links / build docs)
      - name: Setup Node
        if: ${{ inputs.markdown_lint || inputs.link_check || inputs.build_docs }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          # ⚠️ NE PAS mettre "cache: npm" s'il n'y a pas de lockfile

      - name: Install dependencies
        if: ${{ inputs.markdown_lint || inputs.link_check || inputs.build_docs }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          elif [ -f package.json ]; then
            npm install
          else
            echo "No package.json; skipping npm install"
          fi

      - name: Lint Markdown
        if: ${{ inputs.markdown_lint }}
        env:
          MD_CONF: ${{ env.MARKDOWNLINT_CONFIG }}
        run: |
          if [ -n "${MD_CONF}" ]; then
            npx --yes markdownlint-cli@0.41.0 "**/*.md" --ignore "node_modules" --config "${MD_CONF}"
          else
            npx --yes markdownlint-cli@0.41.0 "**/*.md" --ignore "node_modules"
          fi

      - name: Check links (optional)
        if: ${{ inputs.link_check }}
        run: |
          npx --yes markdown-link-check@3 "**/*.md" -q || true

      - name: Build docs (optional)
        if: ${{ inputs.build_docs }}
        run: echo "Build your docs here"
