name: Org Policies Guard
on:
  workflow_call:
    inputs:
      fail_on_warning: { type: boolean, required: false, default: true }
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block disallowed files (secrets/dumps)
        run: |
          set -e
          bad=("id_rsa" ".pem" ".p12" ".env" "dump.sql" "secrets.json" "wasabi_access_key" "b2_application_key")
          for f in "${bad[@]}"; do
            if git ls-files | grep -qi "$f"; then
              echo "::error::Fichier proscrit détecté: $f"; exit 1; fi; done
      - name: Warn on potential PII in dumps
        run: |
          if git grep -nE "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}" -- '*.sql' '*.csv' >/dev/null; then
            echo "::warning::Emails trouvés dans des artefacts potentiels (SQL/CSV). Vérifier l’anonymisation.";
            ${{ inputs.fail_on_warning && 'exit 1' || 'true' }}
          fi
